"""Update relationship

Revision ID: 62819fef05b4
Revises: ccd916e3e182
Create Date: 2021-05-11 01:49:53.423255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62819fef05b4'
down_revision = 'ccd916e3e182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
